### ISSUE TITLE
Create an easily accessible link to the API Reference (where?)

### ISSUE THREAD

**Issue by ewajankowskaview** [viewar/documentation#50]
atw it's hidden at the end of Quickstart section.

**Comment by DoubleU23** [comment]
i also stumbled over this problem yesterday...

@ewajankowskaview 
**shall we add it to the main nav?**

in v2 of docusaurus, we will be able to add extern links to the sidebar.  
Have to try if they have merged it into v1 too...

**Comment by ewajankowskaview** [comment]
Yes, I think we should add it to the main nav.
A link would be great, otherwise, I will prepare a brief introduction page with a link.

**Comment by DoubleU23** [comment]
If you find time for it, please do it.
`/website/siteConfig.js` - headerlinks

Otherwise I'll add it at some point next week...

**Comment by DoubleU23** [comment]
added API page link to header, footer and index-buttons

**Comment by ewajankowskaview** [comment]
Nice, thanks. I also added some additional pages and references (issue #64), so we should be good with that.
